# Development Docker Compose
version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: schoolmanagement-app-dev
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - laravel-network
    depends_on:
      - database
      - redis

  nginx:
    image: nginx:alpine
    container_name: schoolmanagement-nginx-dev
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
    networks:
      - laravel-network

  # Vite Development Server
  vite:
    image: node:20-alpine
    container_name: schoolmanagement-vite
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    command: sh -c "npm install --legacy-peer-deps && npm run dev"
    ports:
      - "5173:5173"
    networks:
      - laravel-network
    environment:
      - CHOKIDAR_USEPOLLING=true

  database:
    image: mysql:8.0
    container_name: schoolmanagement-mysql-dev
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: schoolms_db
      MYSQL_USER: schoolms_user
      MYSQL_PASSWORD: schoolms_password
      MYSQL_ROOT_PASSWORD: root_password
    volumes:
      - schoolms-data-dev:/var/lib/mysql
    networks:
      - laravel-network

  redis:
    image: redis:alpine
    container_name: schoolmanagement-redis-dev
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - laravel-network

volumes:
  schoolms-data-dev:
    driver: local

networks:
  laravel-network:
    driver: bridge