version: '3.8'

services:
  # Laravel Application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: schoolmanagement-app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - laravel-network
    depends_on:
      - database
      - redis
    environment:
      - DB_HOST=database
      - DB_DATABASE=schoolms_db
      - DB_USERNAME=schoolms_user
      - DB_PASSWORD=schoolms_password
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  # Nginx Web Server
  nginx:
    image: nginx:alpine
    container_name: schoolmanagement-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "8080:80"
      - "443:443"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/sites/:/etc/nginx/sites-available
      - ./docker/nginx/ssl/:/etc/ssl/certs
    depends_on:
      - app
    networks:
      - laravel-network

  # MySQL Database
  database:
    image: mysql:8.0
    container_name: schoolmanagement-mysql
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: schoolms_db
      MYSQL_USER: schoolms_user
      MYSQL_PASSWORD: schoolms_password
      MYSQL_ROOT_PASSWORD: root_password
    volumes:
      - schoolms-data:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - laravel-network

  # Redis Cache
  redis:
    image: redis:alpine
    container_name: schoolmanagement-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - laravel-network

  # phpMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: schoolmanagement-phpmyadmin
    restart: unless-stopped
    ports:
      - "8081:80"
    environment:
      PMA_HOST: database
      PMA_PORT: 3306
      PMA_USER: schoolms_user
      PMA_PASSWORD: schoolms_password
      MYSQL_ROOT_PASSWORD: root_password
    depends_on:
      - database
    networks:
      - laravel-network

  # Node.js for development (optional)
  node:
    image: node:18-alpine
    container_name: schoolmanagement-node
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    command: sh -c "npm install && npm run dev"
    ports:
      - "5173:5173"
    networks:
      - laravel-network
    profiles:
      - development

volumes:
  schoolms-data:
    driver: local

networks:
  laravel-network:
    driver: bridge